### ISSUE TITLE
Files required by miRge3 that are not created by miRge3-build

### ISSUE THREAD

**Issue by fmughal** [mhalushka/miRge3_build#3]
Hello,

I was wondering if you could elaborate on the source of the following files (where were they obtained and what sort of pre-processing was done) on the following files. There doesn't seem to be any explanation for these files in the documentation and mirge3-build does not create them from the input files. However, these are critical to the operation of `a2i` and `trf` features of miRge3.
Lastly, I was hoping to confirm the following: 
miRge uses mature miRNA sequences that are extended upto 25 ntd by adding 2 ntd at 5p and 6 ntd at 3p (according to the first miRge publication). Some of the mature miRNAs do not get extended by virtue of their location on the hairpin (falling at extreme ends; mostly 3p miRs suffer from this but occasionally a 5p miR would fall at the beginning of the hairpina s well). The hairpin files that you used for miRge-build and subsequently for the publications, are they preprocessed such that the hairpin sequence is extended to account for this? I ask because I wasn't unable to consistently reproduce this extension of mature miRs through the miRge-build code and had to preprocess the hairpin sequence files (flank them at each end with a certain number of ntds) to accomplish this.

Thank you!

**Comment by arunhpatil** [comment]
Hi @fmughal, 

The algorithm for tRFs are only supported for human and [Genomic tRNA  Database](https://pubmed.ncbi.nlm.nih.gov/18984615/) was used to obtain the annotations for human tRFs. While a2i editing is based on the alignment to the reference small RNA databases and further statistics is applied to rule out false discoveries as explained in the additional file 1 of the [miRge2.0 ](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2287-y#MOESM1)

With regard to flanking sequence, we use genomic sequence flanking precursor sequence to obtain the additional nucleotides that correspond to the start or end of the precursor sequence, (Ideally, we obtain a 30nt sequence from the genomic coordinates spanning the precursor sequence to avoid this issue). This is utilized to detect non-template Vs template nucleotide additions at either end of the miRNA read (isomiRs). If you are building a database other than human, I am happy to help or clarify any further queries you may have. 

Thank you,
Arun.

**Comment by fmughal** [comment]
Thank you @arunhpatil !

With reference to the GtRNADB data, there are two files provided for tRNA in the miRge pre-built library: pre/mature tRNA. I only see the mature tRNA fasta file in the download section, therefore I was wondering was there any preprocessing done on the the mature tRNA files or were the pre-tRNA files downloaded from somewhere else. Also, for mature tRNA sequences, i noticed that `TCCA` at the end of each sequence found on GtRNADB (hg19 and hg38 both) has been changed to `ACCA` in the mature tRNA file in the miRge pre-built libraries. Was there a reason behind this change?

**Comment by arunhpatil** [comment]
Hi @fmughal , 

The pre-tRNA is 100 nucleotides of the mature tRNA and the sequence can be fetched from the coordinates obtained from the Gencode GFF3 file. (Coordinates of mature tRNA: End + 1 to 100 bp downstream for positive strand and coordinates of mature tRNA: End - 1 to 100 bp upstream for negative strand, We call this the trailer). 

The library does not have the mutations of the sequence, however, we have an extension of the sequence with additional nucleotides from the genome to capture any 3' additions in the reads. 
From `miRge3.0`
>Homo_sapiens_tRNA-Ala-AGC-2-2
GGGGGTGTAGCTCAGTGGTAGAGCGCGTGCTTAGCATGCACGAGGCCCCGGGTTCAATCC
CCGGCACC`TCCA`CCA
From `GtRNADB data`
>Homo_sapiens_tRNA-Ala-AGC-2-2 (tRNAscan-SE ID: chr6.trna104) Ala (AGC) 72 bp Sc: 84.7 chr6:28831462-28831533 (-)
GGGGGTGTAGCTCAGTGGTAGAGCGCGTGCTTAGCATGCACGAGGCCCCGGGTTCAATCC
CCGGCACC`TCCA`

I hope this answers your query and let us know if you need any further information. 

Thank you,
Arun.

**Comment by fmughal** [comment]
Thank you, @arunhpatil , this is very helpful! I tremendously appreciate your prompt response. 
I had three more questions:
1). I was wondering if you could also point me to source for the following files (or if any preprocessing was done to obtain them):
* human_tRF_infor.csv 
* human_tRF_merges.csv 
* human_trna_aminoacid_anticodon.csv 
* human_trna_deduplicated_list.csv 
* human_trna.str
* human_mirna_SNP_pseudo_miRBase.fa (I'm guessing this is from miRNASNP)
2). For the following files, could you confirm the approach for the creation of the following files:
* human_miRNAs_in_repetitive_element_miRBase.csv: check for overlap between miRBase and Gencode transcripts (either in genomic coordinates or bowtie alignments) .
* human_merges_miRBase.csv : families of miRs merged on the basis of "near-identity" per miRge 1.0 publication (what was the threshold to determine this: for example,  `n` number of mismatches in a particular region i.e. outside the seed region or something of the sort)
3). Is the latest human.tar.gz set of libraries available to run with miRge 3.0 based entirely on the hg38 build versions from the respective databases?

Thank you!

**Comment by arunhpatil** [comment]
Hi @fmughal, 

I hope this helps. 

1. All about question 1 can be obtained from this [paper ](https://academic.oup.com/jid/article/223/10/1796/5909842) and its extended methods and yes miRNASNP database. 

2. 

- repetitive_element_miRBase.csv => genomic coordinates 

- merges (page 2 of this extended [material](https://static-content.springer.com/esm/art%3A10.1186%2Fs12859-018-2287-y/MediaObjects/12859_2018_2287_MOESM1_ESM.pdf))

3. Yes, it is available [here](https://mirge3.readthedocs.io/en/latest/quick_start.html#mirge3-0-libraries)

Thank you,
Arun.

**Comment by fmughal** [comment]
Thank you @arunhpatil for your help!
