### ISSUE TITLE
Install issues with biopython version

### ISSUE THREAD

**Issue by sudeep71** [mhalushka/miRge3_build#5]
Hi 

I am having trouble installing mirge_build. I was able to install mirge3 using conda and pip but could not install mirge_build. I have tried setting up in a single conda env or separate env's and still run into the install issue.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
mirge3 0.1.4 requires biopython>=1.78, but you have biopython 1.77 which is incompatible.
Successfully installed biopython-1.77 miRge-build-0.0.1 scikit-learn-0.23.1 scipy-1.4.1

**Comment by arunhpatil** [comment]
Hi @sudeep71,

Sorry for the inconvenience caused. I have updated miRge3.0 over this weekend and in 0.1.4 release, I have updated a few things that comply the current changes in most packages with regards to numpy float error for example. However, the changes are being reviewed and pending approval at Bioconda. 

In the meanwhile, can you install the miRge3.0 as shown below:
`pip install mirge3==0.1.2`
This should solve the pip conflicts. 

For your information, you can check the release dates here:
https://github.com/mhalushka/miRge3.0/releases

Conda is yet finalize our latest release by performing pending tests and approve our new release. 

I will update the same in mirge_build, once miRge3.0 is released in conda.

**Comment by sudeep71** [comment]
@arunhpatil,

Thanks for getting back to me so soon. I am now having numpy float error showing up.

These are steps i am using to set the env up
1) conda create -n #name_of _env python=3.8 ipython
2) activate env
3) pip install mirge3==0.1.2
Now comes the numpy error message.

Any help is appreciated.

**Comment by arunhpatil** [comment]
Hi @sudeep71,

Yes, thanks to another user (@Glfrey) who brought up a similar issue and a solution for numpy (https://github.com/mhalushka/miRge3.0/issues/63#issuecomment-1429424254), and your inputs are much appreciated. Thus I updated the new relesae over this weekend and it is being tested on Conda (yet to be approved). 

For now, can you re-install numpy as shown below: 
`python3.8 -m pip install numpy==1.19`
or 
`pip install numpy==1.19`

I will make similar changes to this package as well (to adopt recent changes in all the dependencies) as soon as it is approved in Conda. 

Please let us know if this helps. 

Thank you,
Arun.

**Comment by sudeep71** [comment]
Thanks Arun! I have successfully installed both the build and miRge3 software.
I now have another problem, which i will start in the miRge forum

**Comment by arunhpatil** [comment]
Hi @sudeep71, 

I am glad, let me know if I can be of any support here. 

Thank you,
Arun
