### ISSUE TITLE
Question about small RNA libraries for novel organism

### ISSUE THREAD

**Issue by cement-head** [mhalushka/miRge3_build#6]
Hello,

For the following (required) libraries:
![image](https://github.com/mhalushka/miRge3_build/assets/1056700/a9e11b8f-1745-4e36-8b4f-9bcdab3b9a63)
Where exactly does one find these, or rather how can one generate these for a new genome?

**Comment by arunhpatil** [comment]
Hi @cement-head,

- For miRNAs you should look at either miRBAse/MirGeneDB. 
- For other RNA types,  you can obtain the FASTA records for the genome of interest from Ensembl/NCBI/RNA-central (example: https://useast.ensembl.org/info/data/ftp/index.html). The pre-trna should be created at the user end where the FASTA record contains the first 100 nucleotides upstream to the mature tRNA sequences (based on strand). 

I hope this helps. If the organism of interest is not in the list above, then my suggestion is to contact the authors of MirGeneDB/miRBase and get their support on prediction of miRNAs from the genome of your interest (https://mirgenedb.org/information).

**Comment by cement-head** [comment]
Okay, thanks
